package com.g2u.admin.domain.notification;

public enum NotificationType {
    LOW_STOCK,
    NEW_USER,
    IMPORT_COMPLETE,
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    CATEGORY_UPDATED,
    ORDER_CREATED,
    ORDER_STATUS_CHANGED,
    MARKETPLACE_LOW_STOCK,
    MARKETPLACE_MARGIN_ALERT,
    MARKETPLACE_SKU_CHANGED,
    MARKETPLACE_PRODUCT_DELISTED,
    SYSTEM
}
