package com.g2u.admin.service;

import com.g2u.admin.domain.tenant.Tenant;
import com.g2u.admin.domain.tenant.TenantRepository;
import com.g2u.admin.domain.webhook.WebhookEndpointRepository;
import com.g2u.admin.web.dto.CreateWebhookRequest;
import com.g2u.admin.web.dto.UpdateWebhookRequest;
import com.g2u.admin.web.dto.WebhookEndpointDto;
import com.g2u.admin.web.exception.ResourceNotFoundException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.test.context.ActiveProfiles;

import java.util.List;
import java.util.Map;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@ActiveProfiles("test")
class WebhookServiceIntegrationTest {

    @Autowired
    private WebhookService webhookService;

    @Autowired
    private WebhookEndpointRepository webhookEndpointRepository;

    @Autowired
    private TenantRepository tenantRepository;

    private UUID tenantAId;
    private UUID tenantBId;

    @BeforeEach
    void setUp() {
        Tenant tenantA = Tenant.builder()
                .name("Tenant A")
                .slug("tenant-a-" + UUID.randomUUID().toString().substring(0, 8))
                .active(true)
                .build();
        tenantA = tenantRepository.save(tenantA);
        tenantAId = tenantA.getId();

        Tenant tenantB = Tenant.builder()
                .name("Tenant B")
                .slug("tenant-b-" + UUID.randomUUID().toString().substring(0, 8))
                .active(true)
                .build();
        tenantB = tenantRepository.save(tenantB);
        tenantBId = tenantB.getId();
    }

    @Test
    void createWebhook_shouldPersistWithUrlEventsAndAutoGeneratedSecret() {
        CreateWebhookRequest request = new CreateWebhookRequest(
                "https://example.com/webhook",
                List.of("product.created", "product.updated")
        );

        WebhookEndpointDto webhook = webhookService.createWebhook(tenantAId, request);

        assertNotNull(webhook.id());
        assertEquals("https://example.com/webhook", webhook.url());
        assertEquals(List.of("product.created", "product.updated"), webhook.events());
        assertNotNull(webhook.secret());
        assertFalse(webhook.secret().isBlank(), "Secret should be auto-generated and non-blank");
        assertTrue(webhook.active());
        assertEquals(tenantAId, webhook.tenantId());
        assertNotNull(webhook.createdAt());
    }

    @Test
    void listWebhooks_shouldReturnWebhooksForTenant() {
        webhookService.createWebhook(tenantAId, new CreateWebhookRequest(
                "https://example.com/hook1", List.of("product.created")));
        webhookService.createWebhook(tenantAId, new CreateWebhookRequest(
                "https://example.com/hook2", List.of("product.deleted")));

        Page<WebhookEndpointDto> webhooks = webhookService.getWebhooks(tenantAId, PageRequest.of(0, 20));

        assertTrue(webhooks.getTotalElements() >= 2);
        webhooks.getContent().forEach(w -> assertEquals(tenantAId, w.tenantId()));
    }

    @Test
    void updateWebhook_shouldChangeUrlAndActiveStatus() {
        WebhookEndpointDto created = webhookService.createWebhook(tenantAId, new CreateWebhookRequest(
                "https://original.com/hook", List.of("product.created")));

        UpdateWebhookRequest updateRequest = new UpdateWebhookRequest(
                "https://updated.com/hook", null, false);

        WebhookEndpointDto updated = webhookService.updateWebhook(tenantAId, created.id(), updateRequest);

        assertEquals("https://updated.com/hook", updated.url());
        assertFalse(updated.active());
        // Events should remain unchanged since we passed null
        assertEquals(List.of("product.created"), updated.events());
    }

    @Test
    void deleteWebhook_shouldRemoveEndpoint() {
        WebhookEndpointDto created = webhookService.createWebhook(tenantAId, new CreateWebhookRequest(
                "https://example.com/to-delete", List.of("product.created")));

        webhookService.deleteWebhook(tenantAId, created.id());

        assertThrows(ResourceNotFoundException.class, () ->
                webhookService.getWebhook(tenantAId, created.id()));
    }

    @Test
    void tenantIsolation_webhookFromTenantANotAccessibleByTenantB() {
        WebhookEndpointDto created = webhookService.createWebhook(tenantAId, new CreateWebhookRequest(
                "https://example.com/isolated", List.of("product.created")));

        // Tenant B cannot get Tenant A's webhook
        assertThrows(ResourceNotFoundException.class, () ->
                webhookService.getWebhook(tenantBId, created.id()));

        // Tenant B list should not contain Tenant A's webhooks
        Page<WebhookEndpointDto> tenantBWebhooks = webhookService.getWebhooks(tenantBId, PageRequest.of(0, 20));
        boolean found = tenantBWebhooks.getContent().stream()
                .anyMatch(w -> w.id().equals(created.id()));
        assertFalse(found, "Tenant B should not see Tenant A webhooks");
    }

    @Test
    void dispatch_withNoActiveEndpoints_shouldNotFail() {
        // Fire-and-forget: dispatching to a tenant with no active endpoints should complete without error
        assertDoesNotThrow(() ->
                webhookService.dispatch(tenantAId, "product.created", Map.of(
                        "productId", UUID.randomUUID().toString(),
                        "name", "Test Product"
                ))
        );
    }
}
